disable *all* of systemd-udevd for faster tests
To restore Mininet's startup performance:

systemctl stop systemd-udevd systemd-udevd-kernel.socket \
             systemd-udevd-control.socket

diff --git a/.github/workflows/run-tests.yaml b/.github/workflows/run-tests.yaml
--- a/.github/workflows/run-tests.yaml
+++ b/.github/workflows/run-tests.yaml
@@ -23,8 +23,9 @@ jobs:
           # sudo apt-get upgrade -y -qq
           PYTHON=${{ matrix.py }} util/install.sh -nv
       - name: Disable slow udevd
-        run: |
-          sudo systemctl stop systemd-udevd || echo "couldn't disable udevd"
+        run: systemctl stop systemd-udevd systemd-udevd-kernel.socket \
+             systemd-udevd-control.socket \
+             || echo "couldn't disable udevd"
       - name: Sanity test
         run: |
           export sudo="sudo env PATH=$PATH"
